### PR TITLE
Fix user name with spaces not working

### LINKED ISSUE #9: User name with spaces doesnt work
When I try to create a user with spaces it crashes. You can easily simulate this by putting a space into username in the test `TestAccBitbucketUser` like this `name = "admin %v"`

```
=== RUN   TestAccBitbucketUser
    TestAccBitbucketUser: testing.go:568: Step 0 error: errors during apply:
        
        Error: API Error: 404 /rest/api/1.0/users/admin+7292545641539942086 User admin+7292545641539942086 does not exist.
        
        
          on /var/folders/t6/mhc7m08j29d0jvfzxc2_zzr40000gn/T/tf-test963642486/main.tf line 2:
          (source code not available)
        
        
    TestAccBitbucketUser: testing.go:629: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during refresh: failed to get user admin 7292545641539942086 from bitbucket: API Error: 404 /rest/api/1.0/users/admin+7292545641539942086 User admin+7292545641539942086 does not exist.
        
        
        State: <nil>
--- FAIL: TestAccBitbucketUser (0.20s)
```

### PR DESCRIPTION
**Pull request by Kamahl19**
This PR fixes #9 which makes it impossible to create user with space in his username. This is perfectly valid when creating user via UI

### CODE REVIEW

**Comment by gavinbunney** [comment]
Nice thanks!
